@startuml
class VisibilityTest {
    -privateField: String
    #protectedField: int
    ~packageField: double
    +publicField: boolean
    
    -privateMethod(): void
    #protectedMethod(): String
    ~packageMethod(): int
    +publicMethod(): boolean
}
@enduml
